version: '3.8'

services:
  auth:
    build: 
      context: ./auth
      dockerfile: Dockerfile.dev
    container_name: tm_auth
    environment:
      - AUTH_PORT=${AUTH_PORT}
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_DB_NAME=${DB_NAME}
      - AUTH_SERVICE_NAME=${AUTH_SERVICE_NAME}
    develop:
      watch:
        - path: ./auth/package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        - path: ./auth
          target: /app
          action: sync
  tickets:
    build: 
      context: ./tickets
      dockerfile: Dockerfile.dev
    container_name: tm_tickets
    environment:
      - TICKET_PORT=${TICKET_PORT}
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - TICKET_DB_NAME=${DB_NAME}
      - TICKET_SERVICE_NAME=${AUTH_SERVICE_NAME}
    develop:
      watch:
        - path: ./tickets/package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        - path: ./tickets
          target: /app
          action: sync

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth
